### ISSUE TITLE
Fails to load diagram - Problem with path?

### ISSUE THREAD

**Issue by partlythomas** [mutcher/jekyll-drawio#15]
I love the idea and simplicity of this plugin - However I am struggling to get it to work.
I have .md posts in a '_posts/' directory. When I try to reference a .drawio file from a md-file in this directory, I get the following problems:

File hierarchy where I have a diagram in two different locations.
```
-_posts/
--post1.md
--architecture-diagram.drawio
-_assets/
--posts/
---post1/
----architecture-diagram.drawio
```

Reference in _posts/post1.md:
```
{% drawio path="_posts/architecture-diagram.drawio" page_number=0 height=300 %}
```

This is not a relative path from the directory of the .md file. This reference builds successfully, but I am only receiving "Error loading file" in the Diagrams viewer.

If i use the following path in _posts/post1.md I am defining the path as a relative path from the .md file where the call is made
```
{% drawio path="../assets/posts/post1/architecture-diagram.drawio" page_number=0 height=300 %}
```

This reference fails at build with the following error:
```
path="..assets/posts/post1/architecture-diagram.drawio" page_num=0
  Liquid Exception: No such file or directory @ rb_sysopen - ..assets/posts/post1/architecture-diagram.drawio in *snip*/_posts/post1.md
```

I find it weird that it says no file or directory IN the .md file - Should it not take into account the directory, not the file? Does this mess up the relative pathing?

I'd very much like to see a working example for this, to verify that I am not using it wrong.

**Comment by mutcher** [comment]
Hi @partlythomas, 

I'm checking this issue in the background. One thing that looks strange is the logs that Jekyll produced,
It says it cannot find the following path - "..assets/posts/post1/architecture-diagram.drawio". As you can see there is no forward slash symbol after two dots, I would expect to have something like "../assets/posts/post1/architecture-diagram.drawio".
Could you please double-check your markdown file once again?

**Comment by mutcher** [comment]
So, I remembered how Jekyll and the plugin process files.
Long story short, if you want to use the file from another folder that is a part of your project you may change the code to:
```
{% drawio path="assets/posts/post1/architecture-diagram.drawio" page_number=0 height=300 %}
```
I tested this code, the example can be found at https://github.com/mutcher/mutcher.github.io/blob/potential-plugin-issue/_posts/2023-04-16-welcome-to-jekyll.markdown.

P.S. I tested the example on the WSL2 with Ubuntu:
```
$ uname -a
Linux 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by partlythomas** [comment]
Thank you @mutcher - The format you refer to is also the one that I've managed to have successfully build for me. However, the diagram viewer still fails to open the file. I'll take a closer look at all the dependencies in your gemfile and try to adjust mine accordingly to see if that could be it.

**Comment by partlythomas** [comment]
Ha! Turns out I was just using the wrong version of your plugin! For some reason I had 1.0.0 defined. Changing to 1.1 instantly made my diagrams appaear properly.

**Comment by partlythomas** [comment]
Closing issue was the problem was just wrong version use.
